// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5astu2F0gl3729tFW5qaFjXjs5jeJEAA',
    appId: '1:763672948367:web:054863cab7f7bb586e4afa',
    messagingSenderId: '763672948367',
    projectId: 'dogshare-e34a2',
    authDomain: 'dogshare-e34a2.firebaseapp.com',
    storageBucket: 'dogshare-e34a2.firebasestorage.app',
    measurementId: 'G-YTK8G2BQS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4muCS0wao_JTD6FXtUSH7mX5VnYtHIVQ',
    appId: '1:763672948367:android:eef022f0d22b884c6e4afa',
    messagingSenderId: '763672948367',
    projectId: 'dogshare-e34a2',
    storageBucket: 'dogshare-e34a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXpesYASVwuVypH_OLdGaYxhugLlSclo',
    appId: '1:763672948367:ios:7d8c72777f3560586e4afa',
    messagingSenderId: '763672948367',
    projectId: 'dogshare-e34a2',
    storageBucket: 'dogshare-e34a2.firebasestorage.app',
    iosBundleId: 'com.example.dogShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvXpesYASVwuVypH_OLdGaYxhugLlSclo',
    appId: '1:763672948367:ios:7d8c72777f3560586e4afa',
    messagingSenderId: '763672948367',
    projectId: 'dogshare-e34a2',
    storageBucket: 'dogshare-e34a2.firebasestorage.app',
    iosBundleId: 'com.example.dogShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5astu2F0gl3729tFW5qaFjXjs5jeJEAA',
    appId: '1:763672948367:web:d7a84683244d4d736e4afa',
    messagingSenderId: '763672948367',
    projectId: 'dogshare-e34a2',
    authDomain: 'dogshare-e34a2.firebaseapp.com',
    storageBucket: 'dogshare-e34a2.firebasestorage.app',
    measurementId: 'G-YEJTJRQ7YF',
  );
}
